sudo: required
dist: trusty

language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly


before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libllvm3.8 llvm-3.8 llvm-3.8-dev llvm-3.8-runtime libffi-dev libclang-3.8-dev clang-3.8
        - sudo apt-get build-dep libffi6
        - sudo rm -rf /usr/local/clang-*
        - ls -l /usr/bin/llvm-config*
        - sudo rm -f /usr/bin/llvm-config && sudo ln -s /usr/bin/llvm-config-3.8 /usr/bin/llvm-config
        - llvm-config --version
        - which llvm-config
        - ./build-runtime-lib.sh
        - export RUST_TEST_THREADS=1

script:
        - (cd libcobra && cargo build)
        - (cd cobrai && cargo build)
        - (cd cobrac && cargo build)
        - cargo test --all
