sudo: required
dist: trusty

language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly


before_install:
        - sudo sh -c "echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main' >> /etc/apt/sources.list"
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-get -qq update
        - sudo apt-get install -y libllvm3.8 llvm-3.8 llvm-3.8-dev
