sudo: required
dist: trusty

language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly


before_install:
        - sudo bash -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" > /etc/apt/sources.list.d/llvm4.list'
        - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - 
        - sudo apt-get -qq update
        - sudo apt-get remove -y llvm
        - sudo apt-get install -y llvm-4.0 llvm-4.0-dev llvm-4.0-runtime lld-4.0
        - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-4.0 200
        - which llvm-config
        - llvm-config --version
        - export RUST_TEST_THREADS=1

script:
        - cargo build
        - cargo test --all
        - ./run_compiler_tests.sh
