sudo: required
dist: trusty

language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly


before_install:
        - sudo sh -c "echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main' >> /etc/apt/sources.list"
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo dpkg -l | grep llvm  
        - sudo apt-get -y remove llvm llvm-3.4 llvm-3.4-dev llvm-runtime llvm-3.4-runtime libllvm3.4
        - sudo apt-get -qq update
        - sudo apt-get install -y libllvm3.8 llvm-3.8 llvm-3.8-dev llvm-3.8-runtime
        - ls -l /usr/bin/llvm-config*  
        - sudo rm -f /usr/bin/llvm-config && sudo ln -s /usr/bin/llvm-config-3.8 /usr/bin/llvm-config 
        - llvm-config --version  
        - llvm-config-3.8 --version  
        - ls -l /usr/bin/llvm-config-3.8 
        - sudo dpkg -l | grep llvm
