[package]
name = "nomad"
version = "0.1.0"
authors = ["Joris Guisson <joris.guisson@gmail.com>"]

[dependencies]
clap = "2.*"
itertools = "0.5"
uuid = { version = "0.2", features = ["v4"] }
llvm-sys = "40"
libc = "*"