[package]
name = "cobrac"
version = "0.1.0"
authors = ["Joris Guisson <joris.guisson@gmail.com>"]
workspace = ".."

[dependencies]
libcobra = { path = "../libcobra" }
clap = "2.20"
llvm-sys = "38"
libc = "*"
shrust = "0.0.4"
itertools = "0.5"

