[package]
name = "libcobra"
version = "0.1.0"
authors = ["Joris Guisson <joris.guisson@gmail.com>"]
workspace = ".."

[dependencies]
itertools = "0.5"
uuid = { version = "0.2", features = ["v4"] }
shrust = "0.0.4"
serde = "0.9"
serde_derive = "0.9"
serde_cbor = "0.5"
